export const theme = {
    bgColor: "#f8f8f8",
    primaryColor: "coral",
    secondaryColor: "oldlace",
    tertiaryColor: "#2196f3",
    white: "white",
    margin: 8,
    padding: 8,
    fontSize: 8,
    fontWeight: 100,
    width: 8,
    height: 8,
    borderRadius: 8,
    borderColor: "#c0c0c0",
    borderWidth: 1,
};
